import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const distDir = path.join(root, 'dist');
const mediaSrcDir = path.join(root, 'media');
const mediaDistDir = path.join(distDir, 'media');

const htmlOrder = [
  '01-header.html',
  '02-hero.html',
  '02-badges.html',
  '08-trust.html',
  '03-courses.html',
  '04-reviews.html',
  '09-start.html',
  '06-projects.html',
  '07-stats.html',
  '03-benefits.html',
  '05-faq.html',
  '10-contact.html',
  '11-footer.html',
];

// This keeps the original cascade and script execution order from the old file.
const assetOrder = [
  '10-contact',
  '11-footer',
  '05-faq',
  '08-trust',
  '07-stats',
  '06-projects',
  '09-start',
  '04-reviews',
  '03-courses',
  '03-benefits',
  '02-badges',
  '02-hero',
  '01-header',
];

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8').trim();
}

function withSourceComment(type, file, content) {
  return '/* ' + type + ': ' + file + ' */\n' + content;
}

const blocks = htmlOrder
  .map((file) => '<!-- block: ' + file + ' -->\n' + read('src/blocks/' + file))
  .join('\n\n');

const css = assetOrder
  .map((name) => withSourceComment('css', name + '.css', read('src/css/' + name + '.css')))
  .join('\n\n');

const js = assetOrder
  .map((name) => withSourceComment('js', name + '.js', read('src/js/' + name + '.js')))
  .join('\n\n');

const tilda = blocks + '\n\n<style>\n' + css + '\n</style>\n\n<script>\n' + js + '\n</script>\n';
const preview = '<!DOCTYPE html>\n<html lang="ru">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>\u041a\u0438\u0431\u0435\u0440\u0423\u043c</title>\n  <style>\n    body { margin: 0; }\n' + css + '\n  </style>\n</head>\n<body>\n' + blocks + '\n\n<script>\n' + js + '\n</script>\n</body>\n</html>\n';

fs.mkdirSync(distDir, { recursive: true });
fs.writeFileSync(path.join(distDir, 'tilda.html'), tilda, 'utf8');
fs.writeFileSync(path.join(distDir, 'preview.html'), preview, 'utf8');
fs.writeFileSync(path.join(root, 'index.html'), '<!-- Generated by scripts/build.mjs. Edit src/ and run npm run build. -->\n' + preview, 'utf8');

// Keep local previews in dist working with relative media paths.
if (fs.existsSync(mediaSrcDir)) {
  fs.mkdirSync(mediaDistDir, { recursive: true });
  fs.cpSync(mediaSrcDir, mediaDistDir, { recursive: true });
}

console.log('Built dist/tilda.html, dist/preview.html, and index.html');
